[package]
name = "rust-calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
pest = "2.7"
pest_derive = "2.7"
web-sys = { version = "0.3", features = ["console"] } 